### Mastering Numerical Computing with NumPy - Umit Mert Cakmak, Mert Cuhadaroglu

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6]])

In [3]:
x.nbytes

24

In [6]:
Data_Cancer= np.random.rand(100000,100)

print(Data_Cancer.dtype)

print(Data_Cancer.nbytes)

Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)

print(Data_Cancer_New.nbytes)

float64
80000000
40000000


In [7]:
'''As you can see from the preceding code, their size decreases from 80 MB to 40 MB just by changing the dtype.
What we get in return is less precision after decimal points. Instead of being precise to 16 decimals points, 
you will have only 7 decimals. '''

'As you can see from the preceding code, their size decreases from 80 MB to 40 MB just by changing the dtype.\nWhat we get in return is less precision after decimal points. Instead of being precise to 16 decimals points, \nyou will have only 7 decimals. '

In [8]:
x = np.asarray([1,2,3,4,5])

x

array([1, 2, 3, 4, 5])

In [9]:
np.arange(1, 8, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [10]:
np.linspace(1, 8, num=13)

array([1.        , 1.58333333, 2.16666667, 2.75      , 3.33333333,
       3.91666667, 4.5       , 5.08333333, 5.66666667, 6.25      ,
       6.83333333, 7.41666667, 8.        ])

In [15]:
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

In [16]:
np.logspace(1, 10, num=5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [17]:
np.logspace(np.log10(1), np.log10(10), num=5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [21]:
x = np.array([0,1,2])
y = np.array([0,1,2])

x == y

array([ True,  True,  True])

In [22]:
np.array_equal(x, y) # when array is too large to see each individual comparison, or you want just one final answer

True

In [23]:
np.logical_or(x, y)

array([False,  True,  True])

In [24]:
np.logical_and(x, y)

array([False,  True,  True])

In [27]:
x = np.array([11, 9, 84, 32])

np.max(x)

84

In [29]:
np.argmax(x) # gives the index of the maximum value

2

In [30]:
import numpy.ma

In [31]:
x = np.arange(6)

In [32]:
x

array([0, 1, 2, 3, 4, 5])

In [33]:
x.mean()

2.5

In [40]:
masked_array = numpy.ma.masked_array(x, mask=[0]) # don't know what masked_array does. Need to explore further

masked_array

masked_array(data=[0, 1, 2, 3, 4, 5],
             mask=[False, False, False, False, False, False],
       fill_value=999999)

In [44]:
x = np.array([3,4,1,0,2,5])

In [45]:
np.where(x<3) # returns indices where value in x is less than 3

(array([2, 3, 4], dtype=int64),)

In [47]:
x[np.where(x<3)] # returns values in an array where value in x is less than 3

array([1, 0, 2])

In [57]:
x = np.array([[11,22,33], [44,55,66], [35, 88, 99]])

In [58]:
x

array([[11, 22, 33],
       [44, 55, 66],
       [35, 88, 99]])

In [59]:
np.where(x>40)

(array([1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 1, 2], dtype=int64))

In [60]:
# In the above, the 1st array is the row-numbers and the 2nd array is the corresponding column-numbers

In [62]:
# https://stackoverflow.com/questions/33747908/output-of-numpy-wherecondition-is-not-an-array-but-a-tuple-of-arrays-why

In [63]:
# https://stackoverflow.com/users/2937831/jakevdp

In [64]:
# https://stackoverflow.com/questions/16343752/numpy-where-function-multiple-conditions

In [65]:
'''When you reshape the array, it's just the output that changes the shape of the array temporarily, 
but it does not change the array itself. When you resize the array, it changes the size of the array permanently'''

"When you reshape the array, it's just the output that changes the shape of the array temporarily, \nbut it does not change the array itself. When you resize the array, it changes the size of the array permanently"

In [72]:
a = np.arange(6).reshape(3,2) 
b = np.arange(10).reshape(2,5)

print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [73]:
np.dot(a,b) == np.matmul(a,b)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
np.matmul(a,b) == a@b

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
from numpy.linalg import multi_dot

In [89]:
        a = np.arange(12000).reshape(40,300)
        b = np.arange(15000).reshape(300,50)
        c = np.arange(25000).reshape(50,500)

In [90]:
multi_dot([a, b, c]) == a.dot(b).dot(c)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [91]:
%timeit multi_dot([a, b, c])

3.58 ms ± 209 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [92]:
%timeit a.dot(b).dot(c)

3.09 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [93]:
# multi_dot is faster

In [94]:
a = np.arange(9).reshape(3,3) 
b = np.arange(3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [95]:
np.dot(a,b) == np.inner(a,b)

array([ True,  True,  True])

In [96]:
np.array_equal(np.dot(a,b), np.inner(a,b))

True

In [97]:
np.outer(a,b)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16]])

#### Solving linear equations


In [98]:
A = np.array([[2, 1, 2], [3, 2, 1], [0, 1, 1]])

B = np.array([8,3,4])

A_inv = np.linalg.inv(A)

np.dot(A_inv,B) # this is the solution when Ax = B

array([-0.2, -0.4,  4.4])

In [99]:
# let's solve the same using solve()

np.linalg.solve(A, B)

array([-0.2, -0.4,  4.4])

In [100]:
'''In order to check our results, we can use the allclose() function, which is used to compare two arrays element-wise'''

'In order to check our results, we can use the allclose() function, which is used to compare two arrays element-wise'

In [101]:
x = np.linalg.solve(A, B)

np.allclose(np.dot(A, x), B)

True