### Numpy - Beginner's Guide - Ivan Idris & Numpy Tricks - Matthew Macarty

In [1]:
import numpy as np

In [3]:
a = np.arange(10).reshape(2,5)

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a[0]

array([0, 1, 2, 3, 4])

In [6]:
a[0,:]

array([0, 1, 2, 3, 4])

In [7]:
a[0,...]

array([0, 1, 2, 3, 4])

In [8]:
a[0,1]

1

In [11]:
np.ptp(a) # returns the difference between max & min values

9

In [12]:
np.median(a)

4.5

In [13]:
np.var(a)

8.25

In [14]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
b = np.array([[5,4,6,2,8],[7,4,6,3,0]])

In [38]:
np.argsort(b) # returns indices of sorted array

array([0, 1, 2, 3, 4], dtype=int64)

In [39]:
a = np.array([2,1,4,6,5,])
b = np.array([6,7,8,9,10])

In [40]:
sort_in = np.argsort(a) # will return indices of sorted a
sort_in

array([1, 0, 2, 4, 3], dtype=int64)

In [41]:
print(b[sort_in]) # will return elements of b at the indices of sort_in. Will give index error if out of range of b

[ 7  6  8 10  9]


In [44]:
sort_in = np.argsort(a)[::-1] # sorting the indices in reverse

sort_in

array([3, 4, 2, 0, 1], dtype=int64)

In [49]:
a = np.random.random(10)

In [50]:
a

array([0.94394115, 0.89893435, 0.74695634, 0.4669953 , 0.39239874,
       0.24729265, 0.3321243 , 0.54964248, 0.52369393, 0.64573258])

In [52]:
np.clip(a, 0.5, 0.8) # values in a less than 0.5 become 0.5; those more than 0.8 become 0.8.

array([0.8       , 0.8       , 0.74695634, 0.5       , 0.5       ,
       0.5       , 0.5       , 0.54964248, 0.52369393, 0.64573258])

In [53]:
a.clip(0.5) # any value lower than 0.5 would be made 0.5

array([0.94394115, 0.89893435, 0.74695634, 0.5       , 0.5       ,
       0.5       , 0.5       , 0.54964248, 0.52369393, 0.64573258])

In [54]:
np.random.choice(a, 2) # pick 2 random values from the array

array([0.64573258, 0.24729265])

In [57]:
# Using Non-uniform probability distribution to pick a random number

np.random.choice(np.arange(1,7), 1, p=[0.25, 0.15, 0.10, 0.20, 0.25, 0.05])

array([4])

In [58]:
from itertools import combinations

In [59]:
pool = [x[0]+x[1]+x[2] for x in combinations('ABCDEFGHIJKLMNOPQRSTUVWXYZ', 3)]

In [ ]:
# The above does combinations of 'AB..YZ' letters in combinations of 3, like ABD, XTU etc.

In [61]:
choice = np.random.choice(pool, 3) # selecting 3 random combinations from the pool

choice

array(['CDY', 'MPT', 'EOU'], dtype='<U3')

In [62]:
a = np.array([1,1,2,2,2,3])
a

array([1, 1, 2, 2, 2, 3])

In [63]:
np.unique(a) # shows unique elements of the array

array([1, 2, 3])

In [64]:
np.searchsorted(a, 99) # returns index where the value 99 should be inserted to maintain the sorted order of the array

6

In [65]:
np.searchsorted(a, -5)

0

In [66]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.flat[3] # returns the value at the index of the flattened array 

4

In [70]:
a = np.array([1,2,3,4,5])
b = a + np.array([5,6,7,8,9])

print(a)
print(b)

[1 2 3 4 5]
[ 6  8 10 12 14]


In [74]:
np.allclose(a,b,atol=6) #compares each element to see if they are within the tolerance limit 'atol' of each other

False

In [75]:
np.isclose(a,b,atol=6) #returns boolean array after element-wise comparison like above

array([ True,  True, False, False, False])

In [76]:
a

array([1, 2, 3, 4, 5])

In [77]:
np.multiply(a, 10, where=a>=3) # multiply each element by 10 only when a>=3 condition is met

array([ 6,  7, 30, 40, 50])

In [78]:
np.multiply.reduce(a)

120

In [79]:
np.multiply.accumulate(a)

array([  1,   2,   6,  24, 120], dtype=int32)

In [80]:
a

array([1, 2, 3, 4, 5])

In [82]:
np.where(a<3, True, False) # returns True or False based on the condition

array([ True,  True, False, False, False])